version: '3'
services:
  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
    environment:
      - AZURE_API_KEY=d6***********
      - AZURE_API_BASE=https://openai-***********/
    command: --config /app/config.yaml --detailed_debug
    env_file:
      - .env
